import { desc } from "drizzle-orm";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { getDb } from "@/lib/db";
import { users } from "@/lib/db/schema";
import { formatDateTime } from "@/lib/utils";
import { createUserAction, resetPasswordAction, setUserActiveAction } from "../actions";

export default async function AdminUsersPage() {
  const rows = await getDb().select().from(users).orderBy(desc(users.createdAt));
  return <div className="grid gap-6 xl:grid-cols-[380px_1fr]"><Card><CardHeader><div><h2 className="font-bold">เพิ่มผู้ใช้งาน</h2><p className="mt-1 text-xs text-slate-500">ไม่มี public signup; Admin เป็นผู้สร้างบัญชี</p></div></CardHeader><CardContent><form action={createUserAction} className="space-y-4"><label className="block text-sm font-semibold">ชื่อผู้ใช้<Input name="username" className="mt-1.5" required minLength={3} /></label><label className="block text-sm font-semibold">ชื่อที่แสดง<Input name="displayName" className="mt-1.5" required /></label><label className="block text-sm font-semibold">รหัสผ่านชั่วคราว<Input name="password" type="password" className="mt-1.5" required minLength={12} /></label><label className="block text-sm font-semibold">สิทธิ์<select name="role" className="mt-1.5 min-h-11 w-full rounded-xl border border-slate-200 bg-white px-3 text-sm"><option value="READ_ONLY">Read only</option><option value="ADMIN">Admin</option></select></label><Button className="w-full">สร้างผู้ใช้งาน</Button></form></CardContent></Card><Card><CardHeader><div><h2 className="font-bold">ผู้ใช้งานทั้งหมด</h2><p className="mt-1 text-xs text-slate-500">{rows.length} บัญชี</p></div></CardHeader><CardContent className="space-y-3">{rows.map((user) => <div key={user.id} className="rounded-2xl border border-slate-200 p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="font-bold text-slate-900">{user.displayName}</p><p className="text-sm text-slate-500">@{user.username}</p></div><div className="flex gap-2"><Badge className={user.role === "ADMIN" ? "bg-violet-50 text-violet-700" : "bg-slate-100 text-slate-600"}>{user.role}</Badge><Badge className={user.active ? "bg-emerald-50 text-emerald-700" : "bg-rose-50 text-rose-700"}>{user.active ? "ใช้งาน" : "ปิดใช้งาน"}</Badge></div></div><p className="mt-3 text-xs text-slate-400">Login ล่าสุด: {user.lastLoginAt ? formatDateTime(user.lastLoginAt) : "ยังไม่เคย"}</p><div className="mt-4 flex flex-wrap gap-2"><form action={setUserActiveAction}><input type="hidden" name="id" value={user.id} /><input type="hidden" name="active" value={String(!user.active)} /><Button variant="secondary" size="sm">{user.active ? "ปิดใช้งาน" : "เปิดใช้งาน"}</Button></form><form action={resetPasswordAction} className="flex min-w-64 flex-1 gap-2"><input type="hidden" name="id" value={user.id} /><Input name="password" type="password" placeholder="รหัสผ่านใหม่ ≥ 12 ตัว" minLength={12} required className="min-h-9" /><Button variant="secondary" size="sm">Reset</Button></form></div></div>)}</CardContent></Card></div>;
}

