import { Button } from "@/components/ui/button";
import { Input, Textarea } from "@/components/ui/input";
import { getContentParagraphs } from "@/lib/content-body";
import type { articleGroups, contents } from "@/lib/db/schema";

type Group = typeof articleGroups.$inferSelect;
type Content = typeof contents.$inferSelect;

export function ContentAdminForm({ action, groups, content }: { action: (formData: FormData) => Promise<void>; groups: Group[]; content?: Content }) {
  return <form action={action} className="space-y-5">{content && <input type="hidden" name="id" value={content.id} />}<div className="grid gap-4 sm:grid-cols-2"><label className="block text-sm font-semibold">ประเภท<select name="type" defaultValue={content?.type ?? "NEWS"} className="mt-1.5 min-h-11 w-full rounded-xl border border-slate-200 bg-white px-3 text-sm"><option value="NEWS">ข่าว</option><option value="ARTICLE">บทความ</option></select></label><label className="block text-sm font-semibold">กลุ่ม<select name="groupId" defaultValue={content?.groupId ?? ""} className="mt-1.5 min-h-11 w-full rounded-xl border border-slate-200 bg-white px-3 text-sm"><option value="">ไม่ระบุกลุ่ม</option>{groups.map((group) => <option key={group.id} value={group.id}>{group.name}</option>)}</select></label></div><label className="block text-sm font-semibold">ชื่อเรื่อง<Input name="title" defaultValue={content?.title} className="mt-1.5" required /></label><label className="block text-sm font-semibold">Slug<Input name="slug" defaultValue={content?.slug} className="mt-1.5" pattern="[a-z0-9-]+" required /></label><label className="block text-sm font-semibold">สรุป<Textarea name="summary" defaultValue={content?.summary ?? ""} className="mt-1.5 min-h-24" /></label><div className="grid gap-4 sm:grid-cols-2"><label className="block text-sm font-semibold">ภาพปก (JPG, PNG, WebP ไม่เกิน 5 MB)<Input name="coverImage" type="file" accept="image/jpeg,image/png,image/webp" className="mt-1.5 py-2" /></label><label className="block text-sm font-semibold">คำอธิบายภาพ<Input name="coverAlt" className="mt-1.5" placeholder="คำอธิบายสำหรับ screen reader" /></label></div><label className="block text-sm font-semibold">เนื้อหา <span className="font-normal text-slate-400">(เว้นบรรทัดเพื่อแบ่งย่อหน้า)</span><Textarea name="body" defaultValue={getContentParagraphs(content?.bodyJson).join("\n\n")} className="mt-1.5 min-h-64" required /></label><div className="grid gap-4 sm:grid-cols-2"><label className="block text-sm font-semibold">สถานะ<select name="status" defaultValue={content?.status === "PUBLISHED" ? "PUBLISHED" : "DRAFT"} className="mt-1.5 min-h-11 w-full rounded-xl border border-slate-200 bg-white px-3 text-sm"><option value="DRAFT">ฉบับร่าง</option><option value="PUBLISHED">เผยแพร่</option></select></label><label className="flex min-h-11 items-center gap-3 self-end rounded-xl border border-slate-200 px-4 text-sm font-semibold"><input type="checkbox" name="pinned" defaultChecked={content?.pinned} className="size-4 accent-sky-600" /> ปักหมุดหน้าแรก</label></div><Button>{content ? "บันทึกการแก้ไข" : "สร้างเนื้อหา"}</Button></form>;
}
